version: '3'

services:
  ui:
    build: .
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
      - ./:/usr/src
      - node_modules:/usr/src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
